run:
  timeout: 5m

linters:
  disable:
    - unused
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - ineffassign
    - typecheck
    - gosimple
    - gocyclo
    - misspell

linters-settings:
  gocyclo:
    min-complexity: 200

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
