package theme

// MatrixTheme returns the classic green-on-black Matrix theme
func MatrixTheme() *Theme {
	return &Theme{
		Name:        "matrix",
		Description: "Classic green-on-black terminal aesthetic inspired by The Matrix",
		Colors: ColorsConfig{
			Primary:    "#00FF00",
			Secondary:  "#00CC00",
			Accent:     "#33FF33",
			Background: "#0A0A0A",
			Foreground: "#00FF00",
			Muted:      "#006600",
			Border:     "#003300",
			Error:      "#FF0000",
			Warning:    "#FFFF00",
			Success:    "#00FF00",
			Online:     "#00FF00",
			Away:       "#CCFF00",
			DND:        "#FF0000",
			XA:         "#FF6600",
			Offline:    "#333333",
		},
		Roster: RosterConfig{
			HeaderFg:   "#0A0A0A",
			HeaderBg:   "#00FF00",
			SelectedFg: "#0A0A0A",
			SelectedBg: "#00CC00",
			ContactFg:  "#00FF00",
			GroupFg:    "#33FF33",
			BorderFg:   "#003300",
			UnreadFg:   "#FFFF00",
		},
		Chat: ChatConfig{
			MyMessageFg:          "#0A0A0A",
			MyMessageBg:          "#00CC00",
			TheirMessageFg:       "#00FF00",
			TheirMessageBg:       "#1A1A1A",
			TimestampFg:          "#006600",
			NickFg:               "#33FF33",
			EncryptedIndicator:   "#00FF00",
			UnencryptedIndicator: "#FF0000",
			SystemMessageFg:      "#006600",
			TypingIndicatorFg:    "#CCFF00",
		},
		StatusBar: StatusBarConfig{
			Fg:          "#00FF00",
			Bg:          "#000000",
			ModeNormal:  "#00FF00",
			ModeInsert:  "#FFFF00",
			ModeCommand: "#00FFFF",
			AccountFg:   "#00FF00",
			StatusFg:    "#00FF00",
		},
		CommandLine: CommandLineConfig{
			PromptFg:     "#00FF00",
			InputFg:      "#00FF00",
			InputBg:      "#0A0A0A",
			CursorFg:     "#FFFFFF",
			CompletionFg: "#0A0A0A",
			CompletionBg: "#00CC00",
		},
		Dialogs: DialogsConfig{
			BorderFg:       "#00FF00",
			TitleFg:        "#33FF33",
			ContentFg:      "#00FF00",
			ButtonFg:       "#00FF00",
			ButtonBg:       "#1A1A1A",
			ButtonActiveFg: "#0A0A0A",
			ButtonActiveBg: "#00FF00",
		},
	}
}

// NordTheme returns the Arctic blue Nord theme
func NordTheme() *Theme {
	return &Theme{
		Name:        "nord",
		Description: "Arctic, north-bluish color palette for a calm interface",
		Colors: ColorsConfig{
			Primary:    "#88C0D0",
			Secondary:  "#81A1C1",
			Accent:     "#5E81AC",
			Background: "#2E3440",
			Foreground: "#ECEFF4",
			Muted:      "#4C566A",
			Border:     "#3B4252",
			Error:      "#BF616A",
			Warning:    "#EBCB8B",
			Success:    "#A3BE8C",
			Online:     "#A3BE8C",
			Away:       "#EBCB8B",
			DND:        "#BF616A",
			XA:         "#D08770",
			Offline:    "#4C566A",
		},
		Roster: RosterConfig{
			HeaderFg:   "#2E3440",
			HeaderBg:   "#88C0D0",
			SelectedFg: "#2E3440",
			SelectedBg: "#81A1C1",
			ContactFg:  "#ECEFF4",
			GroupFg:    "#88C0D0",
			BorderFg:   "#3B4252",
			UnreadFg:   "#EBCB8B",
		},
		Chat: ChatConfig{
			MyMessageFg:          "#2E3440",
			MyMessageBg:          "#81A1C1",
			TheirMessageFg:       "#ECEFF4",
			TheirMessageBg:       "#3B4252",
			TimestampFg:          "#4C566A",
			NickFg:               "#88C0D0",
			EncryptedIndicator:   "#A3BE8C",
			UnencryptedIndicator: "#BF616A",
			SystemMessageFg:      "#4C566A",
			TypingIndicatorFg:    "#EBCB8B",
		},
		StatusBar: StatusBarConfig{
			Fg:          "#ECEFF4",
			Bg:          "#3B4252",
			ModeNormal:  "#88C0D0",
			ModeInsert:  "#A3BE8C",
			ModeCommand: "#EBCB8B",
			AccountFg:   "#ECEFF4",
			StatusFg:    "#A3BE8C",
		},
		CommandLine: CommandLineConfig{
			PromptFg:     "#88C0D0",
			InputFg:      "#ECEFF4",
			InputBg:      "#2E3440",
			CursorFg:     "#ECEFF4",
			CompletionFg: "#2E3440",
			CompletionBg: "#81A1C1",
		},
		Dialogs: DialogsConfig{
			BorderFg:       "#88C0D0",
			TitleFg:        "#81A1C1",
			ContentFg:      "#ECEFF4",
			ButtonFg:       "#ECEFF4",
			ButtonBg:       "#3B4252",
			ButtonActiveFg: "#2E3440",
			ButtonActiveBg: "#88C0D0",
		},
	}
}

// GruvboxTheme returns the retro warm Gruvbox theme
func GruvboxTheme() *Theme {
	return &Theme{
		Name:        "gruvbox",
		Description: "Retro groove color scheme with warm, earthy tones",
		Colors: ColorsConfig{
			Primary:    "#EBDBB2",
			Secondary:  "#D5C4A1",
			Accent:     "#FE8019",
			Background: "#282828",
			Foreground: "#EBDBB2",
			Muted:      "#928374",
			Border:     "#3C3836",
			Error:      "#FB4934",
			Warning:    "#FABD2F",
			Success:    "#B8BB26",
			Online:     "#B8BB26",
			Away:       "#FABD2F",
			DND:        "#FB4934",
			XA:         "#FE8019",
			Offline:    "#665C54",
		},
		Roster: RosterConfig{
			HeaderFg:   "#282828",
			HeaderBg:   "#EBDBB2",
			SelectedFg: "#282828",
			SelectedBg: "#D5C4A1",
			ContactFg:  "#EBDBB2",
			GroupFg:    "#FE8019",
			BorderFg:   "#3C3836",
			UnreadFg:   "#FABD2F",
		},
		Chat: ChatConfig{
			MyMessageFg:          "#282828",
			MyMessageBg:          "#83A598",
			TheirMessageFg:       "#EBDBB2",
			TheirMessageBg:       "#3C3836",
			TimestampFg:          "#928374",
			NickFg:               "#8EC07C",
			EncryptedIndicator:   "#B8BB26",
			UnencryptedIndicator: "#FB4934",
			SystemMessageFg:      "#928374",
			TypingIndicatorFg:    "#FABD2F",
		},
		StatusBar: StatusBarConfig{
			Fg:          "#EBDBB2",
			Bg:          "#1D2021",
			ModeNormal:  "#83A598",
			ModeInsert:  "#B8BB26",
			ModeCommand: "#FABD2F",
			AccountFg:   "#EBDBB2",
			StatusFg:    "#B8BB26",
		},
		CommandLine: CommandLineConfig{
			PromptFg:     "#FE8019",
			InputFg:      "#EBDBB2",
			InputBg:      "#282828",
			CursorFg:     "#EBDBB2",
			CompletionFg: "#282828",
			CompletionBg: "#D5C4A1",
		},
		Dialogs: DialogsConfig{
			BorderFg:       "#FE8019",
			TitleFg:        "#EBDBB2",
			ContentFg:      "#EBDBB2",
			ButtonFg:       "#EBDBB2",
			ButtonBg:       "#3C3836",
			ButtonActiveFg: "#282828",
			ButtonActiveBg: "#EBDBB2",
		},
	}
}

// DraculaTheme returns the purple dark Dracula theme
func DraculaTheme() *Theme {
	return &Theme{
		Name:        "dracula",
		Description: "Dark theme with vibrant purple and pink accents",
		Colors: ColorsConfig{
			Primary:    "#BD93F9",
			Secondary:  "#FF79C6",
			Accent:     "#50FA7B",
			Background: "#282A36",
			Foreground: "#F8F8F2",
			Muted:      "#6272A4",
			Border:     "#44475A",
			Error:      "#FF5555",
			Warning:    "#F1FA8C",
			Success:    "#50FA7B",
			Online:     "#50FA7B",
			Away:       "#F1FA8C",
			DND:        "#FF5555",
			XA:         "#FFB86C",
			Offline:    "#6272A4",
		},
		Roster: RosterConfig{
			HeaderFg:   "#282A36",
			HeaderBg:   "#BD93F9",
			SelectedFg: "#282A36",
			SelectedBg: "#FF79C6",
			ContactFg:  "#F8F8F2",
			GroupFg:    "#BD93F9",
			BorderFg:   "#44475A",
			UnreadFg:   "#F1FA8C",
		},
		Chat: ChatConfig{
			MyMessageFg:          "#282A36",
			MyMessageBg:          "#BD93F9",
			TheirMessageFg:       "#F8F8F2",
			TheirMessageBg:       "#44475A",
			TimestampFg:          "#6272A4",
			NickFg:               "#FF79C6",
			EncryptedIndicator:   "#50FA7B",
			UnencryptedIndicator: "#FF5555",
			SystemMessageFg:      "#6272A4",
			TypingIndicatorFg:    "#F1FA8C",
		},
		StatusBar: StatusBarConfig{
			Fg:          "#F8F8F2",
			Bg:          "#21222C",
			ModeNormal:  "#BD93F9",
			ModeInsert:  "#50FA7B",
			ModeCommand: "#F1FA8C",
			AccountFg:   "#F8F8F2",
			StatusFg:    "#50FA7B",
		},
		CommandLine: CommandLineConfig{
			PromptFg:     "#FF79C6",
			InputFg:      "#F8F8F2",
			InputBg:      "#282A36",
			CursorFg:     "#F8F8F2",
			CompletionFg: "#282A36",
			CompletionBg: "#BD93F9",
		},
		Dialogs: DialogsConfig{
			BorderFg:       "#BD93F9",
			TitleFg:        "#FF79C6",
			ContentFg:      "#F8F8F2",
			ButtonFg:       "#F8F8F2",
			ButtonBg:       "#44475A",
			ButtonActiveFg: "#282A36",
			ButtonActiveBg: "#BD93F9",
		},
	}
}
