package theme

// RainbowTheme returns the colorful Rainbow theme
func RainbowTheme() *Theme {
	return &Theme{
		Name:        "rainbow",
		Description: "A colorful, vibrant theme with rounded borders",
		Colors: ColorsConfig{
			Primary:    "#FF6B6B",
			Secondary:  "#4ECDC4",
			Accent:     "#FFE66D",
			Background: "#2D3436",
			Foreground: "#DFE6E9",
			Muted:      "#636E72",
			Border:     "#636E72",
			Error:      "#E74C3C",
			Warning:    "#F39C12",
			Success:    "#27AE60",
			Online:     "#00B894",
			Away:       "#FDCB6E",
			DND:        "#E74C3C",
			XA:         "#E17055",
			Offline:    "#636E72",
		},
		Roster: RosterConfig{
			HeaderFg:   "#2D3436",
			HeaderBg:   "#FF6B6B",
			SelectedFg: "#2D3436",
			SelectedBg: "#4ECDC4",
			ContactFg:  "#DFE6E9",
			GroupFg:    "#FFE66D",
			BorderFg:   "#636E72",
			UnreadFg:   "#FF6B6B",
		},
		Chat: ChatConfig{
			MyMessageFg:          "#2D3436",
			MyMessageBg:          "#4ECDC4",
			TheirMessageFg:       "#DFE6E9",
			TheirMessageBg:       "#3D4446",
			TimestampFg:          "#636E72",
			NickFg:               "#FF6B6B",
			EncryptedIndicator:   "#00B894",
			UnencryptedIndicator: "#E74C3C",
			SystemMessageFg:      "#636E72",
			TypingIndicatorFg:    "#FDCB6E",
		},
		StatusBar: StatusBarConfig{
			Fg:          "#DFE6E9",
			Bg:          "#1E2425",
			ModeNormal:  "#4ECDC4",
			ModeInsert:  "#FF6B6B",
			ModeCommand: "#FFE66D",
			AccountFg:   "#DFE6E9",
			StatusFg:    "#00B894",
		},
		CommandLine: CommandLineConfig{
			PromptFg:     "#FF6B6B",
			InputFg:      "#DFE6E9",
			InputBg:      "#2D3436",
			CursorFg:     "#FFE66D",
			CompletionFg: "#2D3436",
			CompletionBg: "#4ECDC4",
		},
		Dialogs: DialogsConfig{
			BorderFg:       "#FF6B6B",
			TitleFg:        "#FFE66D",
			ContentFg:      "#DFE6E9",
			ButtonFg:       "#DFE6E9",
			ButtonBg:       "#3D4446",
			ButtonActiveFg: "#2D3436",
			ButtonActiveBg: "#4ECDC4",
		},
	}
}
